# Generated by Django 3.2.6 on 2022-04-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=200)),
                ('Sobre_Nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('Tel', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
